version: '3.5'

name: training

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Bangkok
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./Initial-DB.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: the.nuyie@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      TZ: Asia/Bangkok
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local